# Generated by Django 2.2 on 2022-10-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20221005_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name',), 'verbose_name': 'categories', 'verbose_name_plural': 'categoriess'},
        ),
    ]
