# Generated by Django 2.2 on 2022-10-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20221005_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=200, unique=True)),
                ('cart_added_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name',), 'verbose_name': 'cat', 'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='itemsincart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cart', models.IntegerField()),
                ('cart_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.cartlist')),
                ('product_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.products')),
            ],
        ),
    ]
