# Generated by Django 2.2 on 2022-10-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20221010_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='slug',
            new_name='productslug',
        ),
        migrations.AlterField(
            model_name='itemsincart',
            name='cart_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Cartlist'),
        ),
    ]
