# Generated by Django 2.2 on 2022-10-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20221017_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slug',
            new_name='categoriesslug',
        ),
        migrations.AlterField(
            model_name='itemsincart',
            name='cart_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Cartlist'),
        ),
    ]
