# Generated by Django 2.2 on 2022-10-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20221017_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsincart',
            name='cart_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Cartlist'),
        ),
    ]
