# Generated by Django 2.2 on 2022-10-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items_in_cart_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cart_added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
